CREATE TABLE Users (
    uId VARCHAR(255) PRIMARY KEY,
    userId VARCHAR(10) NOT NULL,
    createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    type INT CHECK (type BETWEEN 1 AND 20),
    token VARCHAR(255)
);

