CREATE TABLE Users (
    uId VARCHAR(255) PRIMARY KEY,
    userId VARCHAR(10) NOT NULL UNIQUE,
    createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    loginType INT CHECK (loginType BETWEEN 1 AND 20),
    token VARCHAR(255)
);

CREATE TABLE Scores_Normal (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId VARCHAR(10) NOT NULL,
    score INT NOT NULL,
    playTimeMs INT NOT NULL,
    createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Scores_LimitedTime (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId VARCHAR(10) NOT NULL,
    score INT NOT NULL,
    playTimeMs INT NOT NULL,
    createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);