version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: mydatabase2
      MYSQL_USER: sammy
      MYSQL_PASSWORD: sammy123
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
  
  redis:
    image: redis:alpine
    networks:
      - app-network

  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - app-network

  grafana:
    image: grafana/grafana:8.0.0
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      loki:
        condition: service_started
    environment:
      NODE_ENV: production
      DB_HOST: db
      REDIS_HOST: redis
      DB_PORT: 3306
      DB_USERNAME: sammy
      DB_PASSWORD: sammy123
      DB_DATABASE: mydatabase2
      PACKAGE_NAME: com.WistronEnt.socialmedia.star
      GOOGLE_PRIVATE_KEY: ${GOOGLE_PRIVATE_KEY}
      GOOGLE_CLIENT_EMAIL: ${GOOGLE_CLIENT_EMAIL}
      APPLE_SHARED_SECRET: ${APPLE_SHARED_SECRET}
      ENVIRONMENT: development  # or 'prod'
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      JWT_SECRET: ${JWT_SECRET}
      LOKI_HOST: http://loki:3100
    networks:
      - app-network
    volumes:
      #- .:/app
      - /app/node_modules

networks:
  app-network:

volumes:
  db-data:
  grafana-storage:
