import swaggerJSDoc from 'swagger-jsdoc';
import swaggerUi from 'swagger-ui-express';

const swaggerDefinition = {
  openapi: '3.0.0',
  info: {
    title: 'API Documentation',
    version: '1.0.0',
    description: 'API Documentation generated by swagger-jsdoc',
  },
  servers: [
    {
      url: 'http://localhost:3000',
      description: 'Development server',
    },
  ],
};

const options = {
  swaggerDefinition,
  apis: ['./src/routes/v1/characterEggsRoutes.ts'], // files containing annotations as above
};

const swaggerSpec = swaggerJSDoc(options);

export { swaggerUi, swaggerSpec };
